# Generated by Django 2.1.7 on 2019-07-25 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, default=uuid.uuid4, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='hotel.png', upload_to='')),
                ('address', models.TextField()),
                ('contact_p_name', models.CharField(max_length=50)),
                ('contact_p_email', models.EmailField(blank=True, max_length=30)),
                ('contact_p_phone', models.CharField(max_length=12)),
                ('reward_ratio', models.FloatField(max_length=30)),
                ('unique_id', models.CharField(blank=True, default=uuid.uuid4, max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('reference_number', models.CharField(max_length=300)),
                ('comment', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_obtain', models.IntegerField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('reference_number', models.CharField(blank=True, default=uuid.uuid4, max_length=1000, unique=True)),
                ('v_t_hotel', models.FloatField(max_length=30)),
                ('date', models.CharField(default=django.utils.timezone.now, max_length=50)),
                ('sync', models.BooleanField(default=False)),
                ('unique_id', models.CharField(blank=True, default=uuid.uuid4, max_length=1000, null=True, unique=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.Guest')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.Hotel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('extra_beds', models.IntegerField()),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.Guest')),
                ('meal_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.MealPlan')),
                ('room_allocated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.Room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.RoomType'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='room_allocation_data',
            field=models.ManyToManyField(to='payment_tracker_app.RoomAllocation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.PaymentMode'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_tracker_app.PaymentType'),
        ),
    ]
