# Generated by Django 2.1.7 on 2019-07-09 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reference_number',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=1000, unique=True),
        ),
    ]
